const CREATE_SELLER = "CREATE_SELLER";
const UPDATE_SELLER = "UPDATE_SELLER";
const DELETE_SELLER = "DELETE_SELLER";
const RESET_PASSWORD_SELLER = "RESET_PASSWORD_SELLER";
const FORGET_PASSWORD_SELLER = "FORGET_PASSWORD_SELLER";

module.exports = {
  CREATE_SELLER,
  UPDATE_SELLER,
  DELETE_SELLER,
  RESET_PASSWORD_SELLER,
  FORGET_PASSWORD_SELLER,
};
